[package]
name = "qapro-rs"
version = "0.1.0"
authors = ["yutiansut <yutiansut@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "*"
serde_derive = "1.0"
serde = { version = "1.0", features = ["derive"] } # 序列化

stopwatch = "*"


uuid = { version = "0.8", features = ["serde", "v1", "v4"] }
log = "0.4"
regex = "1"
log4rs = "0.13"


lazy_static = "1.4.0"


csv = "1.1.3"
clap = "2.33"
toml = "0.5"
redis = "0.18.0"
amiquip = "0.4.0"

redis-async = "0.6.3"
actix-redis = "0.9.2"
bson = "0.13.0"
mongodb = {version = "1.1.1", default-features = false, features = ["sync"]}

actix = "0.10.0"
actix-rt = "1.0.0"
actix-web = "3.0.0"
actix-cors = "0.3"
actix-web-actors="3.0.0"


futures="0.3.5"
futures-executor = "^0.3"
futures-test = "^0.3"
futures-util = "^0.3"
async-trait= "*"
chrono-tz= { version = "0.5.3", features = ["serde"] }

chrono = "0.4.19"
thiserror = "1.0"
rand = "0.7"

arrow = { version = "^5.0", features = ["prettyprint"] }
parquet = { version = "^5.0", features = ["arrow"] }
datafusion = "5.0.0"

[dependencies.clickhouse-rs]
git = "https://github.com/suharev7/clickhouse-rs"
branch = "async-await"
default-features = false
features = ["async_std"]